const std = @import("std");

pub const max_names = 5;

pub fn extractHeaderComment(content: []const u8) ?[]const u8 {
    var lines = std.mem.splitScalar(u8, content, '\n');
    var idx: usize = 0;

    while (lines.next()) |line| : (idx += 1) {
        if (idx > 30) break;
        const t = std.mem.trim(u8, line, " \t\r");
        if (t.len == 0) continue;
        if (idx == 0 and std.mem.startsWith(u8, t, "#!")) continue;
        if (isBoilerplate(t)) continue;
        if (std.mem.startsWith(u8, t, "package ") or
            std.mem.startsWith(u8, t, "module ") or
            std.mem.startsWith(u8, t, "import ") or
            std.mem.startsWith(u8, t, "from ") or
            std.mem.startsWith(u8, t, "#include") or
            std.mem.startsWith(u8, t, "use "))
        {
            continue;
        }

        if (std.mem.startsWith(u8, t, "//")) {
            const text = std.mem.trim(u8, t[2..], " \t");
            if (text.len > 0 and !isBoilerplate(text) and !std.mem.startsWith(u8, text, "use ")) return text;
        } else if (std.mem.startsWith(u8, t, "#") and !std.mem.startsWith(u8, t, "#!")) {
            const text = std.mem.trim(u8, t[1..], " \t");
            if (text.len > 0 and !isBoilerplate(text)) return text;
        } else if (std.mem.startsWith(u8, t, "--")) {
            const text = std.mem.trim(u8, t[2..], " \t");
            if (text.len > 0 and !isBoilerplate(text)) return text;
        } else {
            return null;
        }
    }
    return null;
}

pub fn isBoilerplate(s: []const u8) bool {
    if (s.len == 0) return false;
    var lower_buf: [128]u8 = undefined;
    if (s.len > lower_buf.len) return false;
    const lower = std.ascii.lowerString(lower_buf[0..s.len], s);
    const markers = [_][]const u8{
        "copyright",    "license",        "spdx",                    "all rights reserved",
        "generated by", "auto-generated", "automatically generated", "strict",
        "eslint",       "pragma",         "@ts-",                    "@eslint-",
    };
    for (&markers) |m| {
        if (std.mem.indexOf(u8, lower, m) != null) return true;
    }
    return false;
}

pub fn extractIdent(text: []const u8) []const u8 {
    const t = std.mem.trimStart(u8, text, " \t\r");
    var end: usize = 0;
    for (t, 0..) |c, i| {
        if (!std.ascii.isAlphanumeric(c) and c != '_') break;
        end = i + 1;
    }
    return t[0..end];
}

pub fn isIdentChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or c == '_';
}

pub fn isIdent(text: []const u8) bool {
    if (text.len == 0) return false;
    if (!std.ascii.isAlphabetic(text[0]) and text[0] != '_') return false;
    for (text[1..]) |c| if (!isIdentChar(c)) return false;
    return true;
}

pub fn joinNames(names: []const []const u8, allocator: std.mem.Allocator) ![]u8 {
    var result: std.ArrayList(u8) = .empty;
    for (names, 0..) |name, i| {
        if (i > 0) try result.appendSlice(allocator, ", ");
        try result.appendSlice(allocator, name);
    }
    return result.items;
}

pub fn skipGenericParams(s: []const u8) []const u8 {
    const rest = std.mem.trimStart(u8, s, " \t");
    if (rest.len == 0 or rest[0] != '<') return rest;
    var depth: usize = 0;
    for (rest, 0..) |c, i| {
        if (c == '<') {
            depth += 1;
        } else if (c == '>') {
            depth -= 1;
            if (depth == 0) return std.mem.trimStart(u8, rest[i + 1 ..], " \t");
        }
    }
    return rest;
}
